### ISSUE TITLE
Tests break when updating multipart from version 1.0 to 1.1

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.app.testing#14]
The important change between the last green run in Jenkins and https://github.com/zopefoundation/zope.app.testing/actions/runs/11201635743/job/31136794139 is the update of multipart from version 1.0 to 1.1.

That's all I was able to find out until now.
(The usual fixed we applied for multipart 1.0 did not help and they were not necessary because the tests were green with that version.)

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2024-10-24 23:48 -0700:
> ...
>That's all I was able to find out until now.
>(The usual fixed we applied for multipart 1.0 did not help and they were not necessary because the tests were green with that version.)

I have looked at the failed `doctest.rst`.
The problem there is a wrong `Content-Length` (`73` instead of `58`).
The new `multipart` version raises a `MultipartError` in this case
which is ignored because `zope.publisher` calls `multipart.parse_form_data`
with `strict=False` (likely a bad decision).
The request then (wrongly) appears to have no data and the test fails
(due to a `200` rather than a `303` response).

**Comment by agroszer** [comment]
Yeah that `strict=False` feels to be wrong. It caused (well together with a multipart version upgrade) a HUHWHAT moment instead of failing hard.

See https://github.com/zopefoundation/zope.publisher/issues/80

**Comment by d-maurer** [comment]
***@***.*** wrote at 2024-10-25 11:40 +0200:
> ...
>I have looked at the failed `doctest.rst`.
>The problem there is a wrong `Content-Length` (`73` instead of `58`).

I will work on a fix.
